[package]
name = "lsz"
version = "0.8.1"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
anyhow = "1.0"
chrono = "0.4"
ratatui = "0.26"
crossterm = "0.27"
termimad = "0.26"
syntect = "5.0"
# 新增: 用于将 ANSI 字符串转换为 Ratatui Text
ansi-to-tui = "4.0" 
unicode-width = "0.1" 
